name: ci
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        run: |
          docker build -t ghcr.io/${{ github.repository }}/gateway-py:${{ github.sha }} app
          docker push ghcr.io/${{ github.repository }}/gateway-py:${{ github.sha }}
